

const TOKEN_FORMAT_SLICE_LENGTH = 4;
const DELETE_SUCCESS_CODE = 1;
const DELETED_ITEM_COUNT_ONE = 1;

module.exports = {
    TOKEN_FORMAT_SLICE_LENGTH,
    DELETE_SUCCESS_CODE,
    DELETED_ITEM_COUNT_ONE
}